# Configuration file for the Ban System plugin

# You need https://libertybans.org/ for this plugin to work!
# m = minutes, h = hours, d = days, mo = months
# for permanent bans, delete all durations, except the first one, and set it to "perm"
ban-durations:
    - "10m"
    - "1h"
    - "6h"
    - "24h"
    - "7d"


# The radius in which the death message/sound will be seen/heard when someone dies. 1 = 1 Block
death-radius: 100
# Should the plugin send a death message in the chat and/or play a sound when someone dies?
death-message: true
death-sound: true
# Only use sounds that are listet in https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
death-sound-type: ENTITY_WITHER_SPAWN

# Should someone lose one ban after a certain time period? So if the counter is on 2 and the time period passes,
# the counter will go down to 1 and the next ban will only last 1h instead of 6h.

lose-ban-after-time: true
# s = seconds, m = minutes, h = hours, d = days
lose-ban-after-duration: "2h"
# use -1 to remove all bans after the time period
lose-ban-amount: 1
# The title on top oft the boss bar, use %time% to show the remaining time until the next ban is removed
countdown-bossbar-title: "You will lose a ban in %time%"
# the color of the countdown boss bar - possible values: "WHITE", "GREEN", "PINK", "BLUE", "YELLOW", "RED", "PURPLE"
countdown-bossbar-color: "RED"

# Should someone lose ban(s) after getting a kill?
lose-ban-after-kill: true
# use -1 to remove all bans after the time period
lose-ban-amount-on-kill: -1